# Generated by Django 4.2.9 on 2024-10-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='back_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='identity/images'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='front_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='identity/images'),
        ),
    ]
