# Generated by Django 4.2.9 on 2024-11-12 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, choices=[('transfer', 'transfer'), ('withdrawal', 'withdrawal'), ('deposit', 'deposit')], max_length=400)),
                ('confirmation_receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('payment_method', models.CharField(blank=True, choices=[('bank', 'bank'), ('crypto', 'crypto'), ('paypal', 'paypal'), ('cashapp', 'cashapp')], max_length=400)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
