# Generated by Django 4.2.9 on 2024-10-21 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_back_id_image_customuser_front_id_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='expiry_date',
            new_name='expiration_date',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='card',
            name='account',
        ),
        migrations.AddField(
            model_name='card',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('MasterCard', 'MasterCard'), ('Verve', 'Verve'), ('Visa', 'Visa')], max_length=10),
        ),
    ]
