# Generated by Django 4.2.9 on 2024-11-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_tax',
            field=models.BooleanField(default=False),
        ),
    ]
