# Generated by Django 4.2.9 on 2024-10-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_expiry_date_card_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='applied_for_activation',
            field=models.BooleanField(default=False),
        ),
    ]
