# Generated by Django 4.2.9 on 2024-10-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_notification_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=400)),
                ('image', models.FileField(blank=True, null=True, upload_to='support/images/')),
            ],
            options={
                'verbose_name': 'Support',
                'verbose_name_plural': 's',
            },
        ),
    ]
