# Generated by Django 4.2.9 on 2024-10-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_card_applied_for_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='applied_for_activation',
            field=models.IntegerField(default=100),
        ),
    ]
