# Generated by Django 4.2.9 on 2024-10-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'verbose_name': 'Support', 'verbose_name_plural': 'Support'},
        ),
        migrations.AlterField(
            model_name='support',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
