# Generated by Django 4.2.9 on 2024-10-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_card_card_activation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='confirmation_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
