# Generated by Django 4.2.9 on 2024-10-26 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_support_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='status',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='subject',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
