# Generated by Django 4.2.9 on 2024-10-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_confirmation_receipt_account_activation_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='confirmation_payment_amount',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('MONEY_MARKET', 'Money Market'), ('CD', 'Certificate of Deposit (CD)')], max_length=20),
        ),
    ]
