# Generated by Django 4.2.9 on 2024-10-26 01:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_support_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='description',
            field=models.TextField(blank=True, default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='support',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled')], default='Pending', max_length=400),
        ),
        migrations.AlterField(
            model_name='support',
            name='subject',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
