# Generated by Django 4.2.9 on 2024-10-22 13:48

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_account_confirmation_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=app.models.generate_account_number, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('MONEY MARKET', 'Money Market'), ('Certificate of Deposit (CD)', 'Certificate of Deposit (CD)')], max_length=40),
        ),
    ]
