# Generated by Django 4.2.9 on 2024-10-26 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_support_description_alter_support_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
