# Generated by Django 4.2.9 on 2024-10-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_account_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='minimum_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('MONEY MARKET', 'Money Market'), ('CD', 'Certificate of Deposit (CD)')], max_length=40),
        ),
    ]
