# Generated by Django 4.2.9 on 2024-10-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_account_id_document_account_initial_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'verbose_name': 'Transfer', 'verbose_name_plural': 'Transfer'},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='minimum_balance',
            new_name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_opening_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='account',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='account',
            name='investment_history',
        ),
        migrations.RemoveField(
            model_name='account',
            name='penalty_for_early_withdrawal',
        ),
        migrations.RemoveField(
            model_name='account',
            name='proof_of_income',
        ),
        migrations.AddField(
            model_name='account',
            name='beneficiary_id_proof',
            field=models.FileField(blank=True, null=True, upload_to='beneficiary_id_proofs/'),
        ),
        migrations.AddField(
            model_name='account',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='credit_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='credit_cards/'),
        ),
        migrations.AddField(
            model_name='account',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='account',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='account',
            name='overdraft_protection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='proof_of_employment',
            field=models.FileField(blank=True, null=True, upload_to='employment_proofs/'),
        ),
        migrations.AddField(
            model_name='account',
            name='proof_of_funds',
            field=models.FileField(blank=True, null=True, upload_to='proof_of_funds/'),
        ),
        migrations.AddField(
            model_name='account',
            name='utility_bill',
            field=models.FileField(blank=True, null=True, upload_to='utility_bills/'),
        ),
        migrations.AddField(
            model_name='account',
            name='yearly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='term_length',
            field=models.IntegerField(blank=True, help_text='Term length in months', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='transaction_limit',
            field=models.IntegerField(default=1000),
        ),
    ]
