# Generated by Django 4.2.9 on 2024-10-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_customuser_city_customuser_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
