# Generated by Django 4.2.9 on 2024-10-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_loan_interest_loan_loan_term_loan_repayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
