# Generated by Django 4.2.9 on 2024-10-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_loan_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='activation_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='loan',
            name='applied_for_activation',
            field=models.BooleanField(default=False),
        ),
    ]
