# Generated by Django 4.2.9 on 2024-10-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_loan_activation_receipt_loan_applied_for_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
